[package]
name = "fastbuffer_benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5.1"
bytes = "1.5.0"

[[bench]]
name = "buffers"
harness = false

